abum_padre(fermin_jimenez,juana_mama_mama).
abum_padre(fermin_jimenez,juan).
abum_padre(fermin_jimenez,fermin_jr).
abum_padre(fermin_jimenez,mario).
abum_padre(fermin_jimenez,lupita).
abum_padre(fermin_jimenez,regino).
abum_padre(fermin_jimenez,arturo).
abum_padre(fermin_jimenez,javier).
abum_padre(fermin_jimenez,ramon).
abum_madre(maria_rodriguez,juana_mama).
abum_madre(maria_rodriguez,juan).
abum_madre(maria_rodriguez,fermin_jr).
abum_madre(maria_rodriguez,mario).
abum_madre(maria_rodriguez,lupita).
abum_madre(maria_rodriguez,regino).
abum_madre(maria_rodriguez,arturo).
abum_madre(maria_rodriguez,javier).
abum_madre(maria_rodriguez,ramon).
abup_padre(ignacio_martin,jose_ramon_papa).
abup_padre(ignacio_martin,francisco).
abup_padre(ignacio_martin,ignacio).
abup_padre(ignacio_martin,rosa).
abup_madre(maria_luz_martin,jose_ramon_papa).
abup_madre(maria_luz_martin,francisco).
abup_madre(maria_luz_martin,ignacio).
abup_madre(maria_luz_martin,rosa).
padre(jose_ramon_papa,jorge).
padre(jose_ramon_papa,luis).
padre(jose_ramon_papa,jose_ramon).
madre(juana_mama,jorge).
madre(juana_mama,luis).
madre(juana_mama,jose_ramon).
